main: org.superfuntime.sftbet.SFTBet
version: 1.0
name: SFTBet

commands:
    pvp:
        description: Initiate matchmaking in the PvP arena
    bet:
        description: Bet on participating players